# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94fe09a74186292e55c2e7da7dec980a"
name = "announcement-appp"
application_url = "https://shopify-announcement-app-c5dh.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_uris = [
  "https://shopify-announcement-app-c5dh.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

# shopify.app.toml
[shop.metafields.my_app.announcement]
type = "single_line_text_field"
name = "Storefront Announcement Banner"
access.admin = "merchant_read_write"
access.storefront = "public_read"